version: "3.3"

services:

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`00001.cocooning.tech`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"

      - "traefik.http.middlewares.myAdmin.ipWhiteList.sourceRange=172.17.0.1"
      - "traefik.http.routers.whoami.middlewares=myAdmin@docker"
      - "traefik.http.routers.whoami.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=tchube:$$apr1$$DZUjqtsH$$VRKssSgVWzU3YlrCA2H6G1"

# htpasswd = 70rwD<ho1y
    networks:
        - web

networks:
  web:
    external: true